# fly.toml app configuration file for lessons-marketplace-server
app = "lessons-marketplace-server"
primary_region = "ewr"

[build]
  dockerfile = "docker/server/Dockerfile"
  context = "."

[env]
  # Non-sensitive environment variables
  # IMPORTANT: Sensitive values (DB_PASSWORD, JWT_SECRET) must be set as secrets with:
  # fly secrets set DB_PASSWORD=your_password --app lessons-marketplace-server
  # fly secrets set JWT_SECRET=your_secret --app lessons-marketplace-server
  NODE_ENV = "production"
  DB_HOST = "twilight-sky-6674.flycast"
  DB_PORT = "5432"
  DB_NAME = "lessons_marketplace_server"
  DB_USER = "lessons_user3"
  DB_SSL = "false"
  DB_POOL_SIZE = "10"
  PORT = "3000"
  FRONTEND_URL = "https://lessons-marketplace-frontend.fly.dev"
  JWT_EXPIRES_IN = "1h"
  REFRESH_TOKEN_EXPIRES_IN = "7d"

# Run database migrations on deploy
# Using the pre-compiled migration command to avoid building on fly.io
[deploy]
  release_command = "node /app/dist/server/prisma/migrate-deploy.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 