# fly.toml app configuration file generated for lessons-marketplace-frontend
app = "lessons-marketplace-frontend"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "80"
  VITE_API_BASE_URL = "https://lessons-marketplace-dawn-cherry-4121.fly.dev"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "frontend_data"
  destination = "/data" 