services:
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lessons_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API server
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      # Database connection - using individual variables
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=lessons_marketplace
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SSL=false
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/lessons_marketplace?schema=public
      # Other environment variables
      - JWT_SECRET=local-development-secret-key
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:5173}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app/server
      - ./shared:/app/shared

  # Frontend development server
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000}
    depends_on:
      - api
    # Add a network alias to ensure the frontend can reach the API
    networks:
      default:
        aliases:
          - frontend

volumes:
  postgres_data: 