# fly.toml app configuration file generated for lessons-marketplace-dawn-cherry-4121 on 2025-03-13T10:00:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lessons-marketplace-dawn-cherry-4121'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
