# fly.toml app configuration file for lessons-marketplace-frontend
app = "lessons-marketplace-frontend"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    TARGET = "frontend"

# Environment variables - most of these will be populated from .env.production during deployment
[env]
  PORT = "80"
  NODE_ENV = "production"
  CONTAINER_ENV = "true"
  # VITE_API_BASE_URL is read from .env.production during deployment

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  protocol = "tcp"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 