# fly.toml app configuration file generated for lessons-marketplace-dawn-cherry-4121 on 2025-03-13T10:00:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lessons-marketplace-dawn-cherry-4121'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'
  DATABASE_URL = "postgres://postgres:xBnWThWyLkLn3yQ@twilight-sky-6674.internal:5432/lessons_marketplace_dawn_cherry_4121?schema=public"
  JWT_SECRET = "production-jwt-secret-key-change-me"
  JWT_EXPIRES_IN = "1h"
  REFRESH_TOKEN_EXPIRES_IN = "7d"
  
  #Postgres cluster twilight-sky-6674 created
  #Username:    postgres
  #Password:    xBnWThWyLkLn3yQ
  #Hostname:    twilight-sky-6674.internal
  #Flycast:     fdaa:12:bd82:0:1::3
  #Proxy port:  5432
  #Postgres port:  5433
  #Connection string: postgres://postgres:xBnWThWyLkLn3yQ@twilight-sky-6674.flycast:5432

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
