# fly.toml app configuration file for lessons-marketplace-server
app = "lessons-marketplace-server"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    TARGET = "server"

# These environment variables are filled from .env.production during deployment
# Most of these will reference values from .env.production and can be overridden by secrets
[env]
  DB_HOST = "twilight-sky-6674.internal"
  DB_PORT = "5432"
  DB_NAME = "lessons_marketplace"
  DB_USER = "postgres"
  DB_SSL = "false"
  DB_POOL_SIZE = "10"
  NODE_ENV = "production"
  PORT = "3000"
  # FRONTEND_URL is read from .env.production during deployment
  # JWT settings are read from .env.production during deployment
  # Note: Sensitive values like DB_PASSWORD and JWT_SECRET should be set as secrets
  # using 'fly secrets set KEY=VALUE' and not in this file

# Run database migrations on deploy
[deploy]
  release_command = "tsx server/entrypoint.ts --run-migrations-only"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 