services:
  database:
    build:
      context: ..
      dockerfile: docker/database/Dockerfile
    container_name: lessons-marketplace-db-base
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ../env/.env.${profile}
    profiles: ["base", "ci", "prod"]

  database-ci:
    extends: database
    container_name: lessons-marketplace-db-ci
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marcin -d lessons_marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["ci"]

  database-prod:
    extends: database
    container_name: lessons-marketplace-db-prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lessons_user3 -d lessons_marketplace_server"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["prod"]

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: lessons-marketplace-server-base
    restart: "no"
    ports:
      - "3000:3000"
    env_file:
      - ../env/.env.${profile}
    depends_on:
      database:
        condition: service_healthy
    profiles: ["base", "ci", "prod"]

  server-ci:
    extends: server
    container_name: lessons-marketplace-server-ci
    depends_on:
      database-ci:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles: ["ci"]

  server-prod:
    extends: server
    container_name: lessons-marketplace-server-prod
    depends_on:
      database-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://lessons-marketplace-server.fly.dev/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles: ["prod"]

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: lessons-marketplace-frontend-base
    restart: "no"
    ports:
      - "5173:80"
    env_file:
      - ../env/.env.${profile}
    depends_on:
      server:
        condition: service_healthy
    profiles: ["base", "ci", "prod"]

  frontend-ci:
    extends: frontend
    container_name: lessons-marketplace-frontend-ci
    build:
      args:
        VITE_API_BASE_URL: http://server-ci:3000
    depends_on:
      server-ci:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/index.html"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles: ["ci"]

  frontend-prod:
    extends: frontend
    container_name: lessons-marketplace-frontend-prod
    build:
      args:
        VITE_API_BASE_URL: https://lessons-marketplace-server.fly.dev
    depends_on:
      server-prod:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://lessons-marketplace-frontend.fly.dev/index.html"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles: ["prod"]

  # Test service using our dedicated test Dockerfile - standalone version
  test:
    build:
      context: ..
      dockerfile: docker/test/Dockerfile
    container_name: lessons-marketplace-test
    environment:
      - JEST_JUNIT_OUTPUT_DIR=/app/test-results/
      - JEST_JUNIT_OUTPUT_NAME=junit.xml
      - PLAYWRIGHT_HEADLESS=true
      - SKIP_WEB_SERVER=true
      - MOCK_API=false
      - PLAYWRIGHT_TIMEOUT=30000
      - PLAYWRIGHT_ACTION_TIMEOUT=15000
      - PLAYWRIGHT_NAVIGATION_TIMEOUT=20000
      - FRONTEND_URL=http://frontend-ci:80
    depends_on:
      database-ci:
        condition: service_healthy
      frontend-ci:
        condition: service_healthy
      server-ci:
        condition: service_healthy
    profiles: ["ci"]

volumes:
  postgres_data: