services:
  database:
    build:
      context: ..
      dockerfile: docker/database/Dockerfile
    container_name: lessons-marketplace-db
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marcin -d lessons_marketplace"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    profiles: ["default", "test"]

  server:
    build:
      context: ..
      dockerfile: docker/server/Dockerfile
    container_name: lessons-marketplace-server
    restart: "no"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    profiles: ["default", "test"]

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: lessons-marketplace-frontend
    restart: "no"
    depends_on:
      - server
    ports:
      - "5173:80"
    profiles: ["default", "test"]

  # Test service using our dedicated test Dockerfile - standalone version
  tests:
    build:
      context: ..
      dockerfile: docker/test.Dockerfile
    container_name: lessons-marketplace-tests
    profiles: ["test"]
    depends_on:
      database:
        condition: service_healthy
      server:
        condition: service_healthy
      frontend:
        condition: service_started
    environment:
      - JEST_JUNIT_OUTPUT_DIR=/app/test-results/
      - JEST_JUNIT_OUTPUT_NAME=junit.xml
      - PLAYWRIGHT_HEADLESS=true
      - SKIP_WEB_SERVER=true
      - MOCK_API=false
      - PLAYWRIGHT_TIMEOUT=30000
      - PLAYWRIGHT_ACTION_TIMEOUT=15000
      - PLAYWRIGHT_NAVIGATION_TIMEOUT=20000
      - FRONTEND_URL=http://frontend:80
    volumes:
      - ../tests/test-results:/app/test-results
      - ../tests/playwright-report:/app/playwright-report
      - ../tests/screenshots:/app/tests/screenshots
    ipc: host  # Recommended for Chrome to avoid memory issues

volumes:
  postgres_data:
  test-results:
  playwright-report:
  pnpm-store: # Add volume for pnpm store