# fly.toml app configuration file generated for lessons-marketplace-api
app = "lessons-marketplace-dawn-cherry-4121"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  # Database connection settings using individual variables
  # These will be overridden by fly.io's database connection settings if needed
  DB_HOST = "twilight-sky-6674.internal"
  DB_PORT = "5432"
  DB_NAME = "lessons_marketplace_dawn_cherry_4121"
  DB_USER = "postgres"
  DB_SSL = "false"
  # Note: DB_PASSWORD should be set as a secret using 'fly secrets set DB_PASSWORD=your_password'
  # Comma-separated list of allowed frontend URLs
  FRONTEND_URL = "https://lessons-marketplace-frontend.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 