server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Application logs
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-logs
          app: lessons-marketplace
          environment: development
          __path__: /var/log/app/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            component: component
            service: service
      - labels:
          level:
          component:
      - timestamp:
          source: time
          format: RFC3339

  # Client-side logs (Core Web Vitals, user interactions)
  - job_name: client-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: client-logs
          app: lessons-marketplace
          environment: development
          __path__: /var/log/app/client.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            pageGroup: pageGroup
            event_type: event_type
      - labels:
          level:
          pageGroup:
          event_type:
      - timestamp:
          source: time
          format: RFC3339

  # Error logs
  - job_name: error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: error-logs
          app: lessons-marketplace
          environment: development
          __path__: /var/log/app/error.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            component: component
            service: service
      - labels:
          level:
          component:
      - timestamp:
          source: time
          format: RFC3339

  # HTTP access logs
  - job_name: http-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: http-logs
          app: lessons-marketplace
          environment: development
          __path__: /var/log/app/http.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            routeGroup: routeGroup
            method: method
            status: status
      - template:
          source: status_class
          template: "{{ if .status }}{{ .status | substr 0 1 }}xx{{ end }}"
      - labels:
          level:
          routeGroup:
          method:
          status_class:
      - timestamp:
          source: time
          format: RFC3339 