name: GitHub CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  checks: write
  id-token: write
  pages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      PNPM_VERSION: 10.3.0  # Match local environment version
      profile: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetching all history to ensure lock file is included

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create logs directory with proper permissions
        run: |
          sudo mkdir -p logs
          sudo chmod -R 777 logs
          echo "Created logs directory with permissions $(ls -ld logs)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Thorough Docker cleanup
        run: |
          export profile=ci
          # Make script executable
          chmod +x scripts/docker-cleanup.sh
          # Execute thorough cleanup
          sudo ./scripts/docker-cleanup.sh
          pnpm docker:clean

      - name: Deploy components
        id: deploy
        run: |
          export profile=ci
          export RUN_SEED=true
          pnpm docker:deploy:rebuild

      - name: Debug Docker environment
        if: always() # Run even if previous step fails
        run: |
          # Ensure logs directory exists with proper permissions
          sudo mkdir -p logs
          sudo chmod -R 777 logs
          
          # Ensure script is executable and run it with sudo
          sudo chmod +x scripts/debug-docker.sh
          sudo ./scripts/debug-docker.sh
          
          # Ensure logs are accessible
          sudo chmod -R 777 logs
          
          # List debug files if they exist
          echo "=== DEBUG FILES GENERATED ==="
          sudo find logs -type f | sort

      - name: Upload debug logs
        uses: actions/upload-artifact@v4
        if: always() # Upload logs even if previous steps fail
        with:
          name: docker-debug-logs
          path: |
            logs/**/*.log
            logs/**/*.txt
            logs/**/*
          retention-days: 7
          if-no-files-found: warn # Don't fail the build if no logs are found

      - name: Run tests
        if: steps.deploy.outcome == 'success'
        run: export profile=ci && pnpm docker:test:rebuild