name: GitHub CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: read
  checks: write
  id-token: write
  pages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      PNPM_VERSION: 10.3.0  # Match local environment version
      ENV_TYPE: ci
      RUN_SEED: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetching all history to ensure lock file is included

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create logs directory with proper permissions
        run: |
          mkdir -p logs
          chmod -R 777 logs
          echo "Created logs directory with permissions $(ls -ld logs)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Thorough Docker cleanup
        run: pnpm docker:clean

      - name: Deploy components
        id: deploy
        run: pnpm docker:deploy:rebuild

      - name: Debug Docker environment
        if: always() # Run even if previous step fails
        run: |
          # Ensure logs directory exists with proper permissions
          mkdir -p logs
          chmod -R 777 logs
          
          # Ensure script is executable and run it
          chmod +x scripts/debug-docker.sh
          ./scripts/debug-docker.sh
          
          # Ensure logs are accessible
          chmod -R 777 logs
          
          # List debug files if they exist
          echo "=== DEBUG FILES GENERATED ==="
          find logs -type f | sort

      - name: Upload debug logs
        uses: actions/upload-artifact@v4
        if: always() # Upload logs even if previous steps fail
        with:
          name: docker-debug-logs
          path: |
            logs/**/*.log
            logs/**/*.txt
            logs/**/*
          retention-days: 7
          if-no-files-found: warn # Don't fail the build if no logs are found

      - name: Run tests
        if: steps.deploy.outcome == 'success'
        run: |
          mkdir -p tests/results/test-logs
          DEBUG=pw:api pnpm docker:test:rebuild 2>&1 | tee tests/results/test-logs/test-output.log

      - name: Upload test execution logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-execution-logs
          path: tests/results/test-logs/
          retention-days: 30

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: tests/results/playwright-report/
          retention-days: 30
          
      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: |
            tests/results/test-results/
            tests/results/screenshots/
          retention-days: 30
          
      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-traces
          path: tests/results/test-results/traces/
          retention-days: 30